// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: bachelor/bachelor.proto

package proto

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// paramètre d'entrée pour la méthode RndGenerator.
type RndRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RndRequest) Reset() {
	*x = RndRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bachelor_bachelor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RndRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RndRequest) ProtoMessage() {}

func (x *RndRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bachelor_bachelor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RndRequest.ProtoReflect.Descriptor instead.
func (*RndRequest) Descriptor() ([]byte, []int) {
	return file_bachelor_bachelor_proto_rawDescGZIP(), []int{0}
}

// valeur de retour pour la méthode RndGenerator.
type RndReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *RndReply) Reset() {
	*x = RndReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bachelor_bachelor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RndReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RndReply) ProtoMessage() {}

func (x *RndReply) ProtoReflect() protoreflect.Message {
	mi := &file_bachelor_bachelor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RndReply.ProtoReflect.Descriptor instead.
func (*RndReply) Descriptor() ([]byte, []int) {
	return file_bachelor_bachelor_proto_rawDescGZIP(), []int{1}
}

func (x *RndReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_bachelor_bachelor_proto protoreflect.FileDescriptor

var file_bachelor_bachelor_proto_rawDesc = []byte{
	0x0a, 0x17, 0x62, 0x61, 0x63, 0x68, 0x65, 0x6c, 0x6f, 0x72, 0x2f, 0x62, 0x61, 0x63, 0x68, 0x65,
	0x6c, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x6f, 0x70, 0x65, 0x6e, 0x61,
	0x70, 0x69, 0x76, 0x32, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x61, 0x6e, 0x6e,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0c,
	0x0a, 0x0a, 0x52, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x24, 0x0a, 0x08,
	0x52, 0x6e, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x32, 0x5d, 0x0a, 0x07, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x12, 0x52, 0x0a,
	0x0c, 0x52, 0x6e, 0x64, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x11, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6e, 0x64, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x1e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x18, 0x12, 0x16, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x76, 0x31, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x72, 0x6e, 0x64, 0x47, 0x65,
	0x6e, 0x42, 0x76, 0x92, 0x41, 0x6a, 0x12, 0x68, 0x0a, 0x2c, 0x54, 0x72, 0x61, 0x76, 0x61, 0x69,
	0x6c, 0x20, 0x64, 0x65, 0x20, 0x62, 0x61, 0x63, 0x68, 0x65, 0x6c, 0x6f, 0x72, 0x20, 0x67, 0x52,
	0x50, 0x43, 0x20, 0x2d, 0x20, 0x54, 0x61, 0x6d, 0x61, 0x47, 0x6f, 0x20, 0x65, 0x74, 0x20, 0x53,
	0x77, 0x61, 0x67, 0x67, 0x65, 0x72, 0x22, 0x33, 0x0a, 0x0f, 0x54, 0x68, 0x6f, 0x6d, 0x61, 0x73,
	0x20, 0x43, 0x68, 0x65, 0x73, 0x65, 0x61, 0x75, 0x78, 0x1a, 0x20, 0x74, 0x68, 0x6f, 0x6d, 0x61,
	0x73, 0x2e, 0x63, 0x68, 0x65, 0x73, 0x65, 0x61, 0x75, 0x78, 0x40, 0x73, 0x74, 0x75, 0x64, 0x65,
	0x6e, 0x74, 0x73, 0x2e, 0x68, 0x65, 0x76, 0x73, 0x2e, 0x63, 0x68, 0x32, 0x03, 0x30, 0x2e, 0x31,
	0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_bachelor_bachelor_proto_rawDescOnce sync.Once
	file_bachelor_bachelor_proto_rawDescData = file_bachelor_bachelor_proto_rawDesc
)

func file_bachelor_bachelor_proto_rawDescGZIP() []byte {
	file_bachelor_bachelor_proto_rawDescOnce.Do(func() {
		file_bachelor_bachelor_proto_rawDescData = protoimpl.X.CompressGZIP(file_bachelor_bachelor_proto_rawDescData)
	})
	return file_bachelor_bachelor_proto_rawDescData
}

var file_bachelor_bachelor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bachelor_bachelor_proto_goTypes = []interface{}{
	(*RndRequest)(nil), // 0: proto.RndRequest
	(*RndReply)(nil),   // 1: proto.RndReply
}
var file_bachelor_bachelor_proto_depIdxs = []int32{
	0, // 0: proto.Greeter.RndGenerator:input_type -> proto.RndRequest
	1, // 1: proto.Greeter.RndGenerator:output_type -> proto.RndReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bachelor_bachelor_proto_init() }
func file_bachelor_bachelor_proto_init() {
	if File_bachelor_bachelor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bachelor_bachelor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RndRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bachelor_bachelor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RndReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bachelor_bachelor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bachelor_bachelor_proto_goTypes,
		DependencyIndexes: file_bachelor_bachelor_proto_depIdxs,
		MessageInfos:      file_bachelor_bachelor_proto_msgTypes,
	}.Build()
	File_bachelor_bachelor_proto = out.File
	file_bachelor_bachelor_proto_rawDesc = nil
	file_bachelor_bachelor_proto_goTypes = nil
	file_bachelor_bachelor_proto_depIdxs = nil
}
